inherit_from:
  - .rubocop_airbnb.yml
Rails:
  Enabled: true

LineLength:
  Max: 140

AllCops:
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/**/*'
    - 'spec/*'
    - 'node_modules/node-sass/src/libsass/contrib/libsass.spec'
    - 'public/geeks-1.0.1/dist/**/*'

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MutableConstant:
  Enabled: false
